# Generated by Django 3.1.7 on 2022-05-06 06:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('doses', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numDose', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('dataHora', models.DateTimeField()),
                ('idPessoa', models.ForeignKey(db_column='idPessoa', on_delete=django.db.models.deletion.CASCADE, to='app.pessoa')),
                ('idVacina', models.ForeignKey(db_column='idVacina', on_delete=django.db.models.deletion.CASCADE, to='app.vacina')),
            ],
            options={
                'unique_together': {('idPessoa', 'idVacina', 'numDose')},
            },
        ),
    ]
