# Generated by Django 3.1.7 on 2022-05-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aplicacao',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='aplicacao',
            constraint=models.UniqueConstraint(fields=('idPessoa', 'idVacina', 'numDose'), name='unique_pk'),
        ),
    ]
