# Generated by Django 3.1.7 on 2022-05-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220506_0708'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aplicacao',
            name='unique_pk',
        ),
        migrations.AddConstraint(
            model_name='aplicacao',
            constraint=models.UniqueConstraint(fields=('pessoa', 'vacina', 'numDose'), name='unique_pk'),
        ),
    ]
